/**
 * This class is generated by jOOQ
 */
package assets.diseases.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseasesRecord extends org.jooq.impl.UpdatableRecordImpl<assets.diseases.tables.records.DiseasesRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1432412944;

	/**
	 * Setter for <code>diseases.diseases.Disease_ID</code>. 
	 */
	public void setDiseaseId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>diseases.diseases.Disease_ID</code>. 
	 */
	public java.lang.Integer getDiseaseId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>diseases.diseases.Diseases_Desc</code>. 
	 */
	public void setDiseasesDesc(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>diseases.diseases.Diseases_Desc</code>. 
	 */
	public java.lang.String getDiseasesDesc() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>diseases.diseases.Avoid_Food</code>. 
	 */
	public void setAvoidFood(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>diseases.diseases.Avoid_Food</code>. 
	 */
	public java.lang.String getAvoidFood() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>diseases.diseases.Avoid_Nutri</code>. 
	 */
	public void setAvoidNutri(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>diseases.diseases.Avoid_Nutri</code>. 
	 */
	public java.lang.String getAvoidNutri() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>diseases.diseases.Avoid_Exer</code>. 
	 */
	public void setAvoidExer(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>diseases.diseases.Avoid_Exer</code>. 
	 */
	public java.lang.String getAvoidExer() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.diseases.tables.Diseases.DISEASES.DISEASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.diseases.tables.Diseases.DISEASES.DISEASES_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.diseases.tables.Diseases.DISEASES.AVOID_FOOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.diseases.tables.Diseases.DISEASES.AVOID_NUTRI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return assets.diseases.tables.Diseases.DISEASES.AVOID_EXER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getDiseaseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDiseasesDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAvoidFood();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAvoidNutri();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAvoidExer();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DiseasesRecord
	 */
	public DiseasesRecord() {
		super(assets.diseases.tables.Diseases.DISEASES);
	}
}
