/**
 * This class is generated by jOOQ
 */
package assets.fitness.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exercises extends org.jooq.impl.TableImpl<assets.fitness.tables.records.ExercisesRecord> {

	private static final long serialVersionUID = 1890739291;

	/**
	 * The singleton instance of <code>fitness.exercises</code>
	 */
	public static final assets.fitness.tables.Exercises EXERCISES = new assets.fitness.tables.Exercises();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.fitness.tables.records.ExercisesRecord> getRecordType() {
		return assets.fitness.tables.records.ExercisesRecord.class;
	}

	/**
	 * The column <code>fitness.exercises.Exercise_ID</code>. 
	 */
	public final org.jooq.TableField<assets.fitness.tables.records.ExercisesRecord, java.lang.Integer> EXERCISE_ID = createField("Exercise_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>fitness.exercises.Exercise_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.fitness.tables.records.ExercisesRecord, java.lang.String> EXERCISE_DESC = createField("Exercise_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>fitness.exercises.Exercise_Type_ID</code>. 
	 */
	public final org.jooq.TableField<assets.fitness.tables.records.ExercisesRecord, java.lang.Integer> EXERCISE_TYPE_ID = createField("Exercise_Type_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>fitness.exercises.Calorie_Burned</code>. 
	 */
	public final org.jooq.TableField<assets.fitness.tables.records.ExercisesRecord, java.lang.Double> CALORIE_BURNED = createField("Calorie_Burned", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * Create a <code>fitness.exercises</code> table reference
	 */
	public Exercises() {
		super("exercises", assets.fitness.Fitness.FITNESS);
	}

	/**
	 * Create an aliased <code>fitness.exercises</code> table reference
	 */
	public Exercises(java.lang.String alias) {
		super(alias, assets.fitness.Fitness.FITNESS, assets.fitness.tables.Exercises.EXERCISES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.fitness.tables.records.ExercisesRecord, java.lang.Integer> getIdentity() {
		return assets.fitness.Keys.IDENTITY_EXERCISES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.fitness.tables.records.ExercisesRecord> getPrimaryKey() {
		return assets.fitness.Keys.KEY_EXERCISES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.fitness.tables.records.ExercisesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.fitness.tables.records.ExercisesRecord>>asList(assets.fitness.Keys.KEY_EXERCISES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.fitness.tables.Exercises as(java.lang.String alias) {
		return new assets.fitness.tables.Exercises(alias);
	}
}
