/**
 * This class is generated by jOOQ
 */
package assets.fitness.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExercisesRecord extends org.jooq.impl.UpdatableRecordImpl<assets.fitness.tables.records.ExercisesRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double> {

	private static final long serialVersionUID = 424852984;

	/**
	 * Setter for <code>fitness.exercises.Exercise_ID</code>. 
	 */
	public void setExerciseId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>fitness.exercises.Exercise_ID</code>. 
	 */
	public java.lang.Integer getExerciseId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fitness.exercises.Exercise_Desc</code>. 
	 */
	public void setExerciseDesc(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>fitness.exercises.Exercise_Desc</code>. 
	 */
	public java.lang.String getExerciseDesc() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fitness.exercises.Exercise_Type_ID</code>. 
	 */
	public void setExerciseTypeId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>fitness.exercises.Exercise_Type_ID</code>. 
	 */
	public java.lang.Integer getExerciseTypeId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>fitness.exercises.Calorie_Burned</code>. 
	 */
	public void setCalorieBurned(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>fitness.exercises.Calorie_Burned</code>. 
	 */
	public java.lang.Double getCalorieBurned() {
		return (java.lang.Double) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.fitness.tables.Exercises.EXERCISES.EXERCISE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.fitness.tables.Exercises.EXERCISES.EXERCISE_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return assets.fitness.tables.Exercises.EXERCISES.EXERCISE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return assets.fitness.tables.Exercises.EXERCISES.CALORIE_BURNED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getExerciseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getExerciseDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getExerciseTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getCalorieBurned();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExercisesRecord
	 */
	public ExercisesRecord() {
		super(assets.fitness.tables.Exercises.EXERCISES);
	}
}
