/**
 * This class is generated by jOOQ
 */
package assets.diseases.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diseases extends org.jooq.impl.TableImpl<assets.diseases.tables.records.DiseasesRecord> {

	private static final long serialVersionUID = 382472532;

	/**
	 * The singleton instance of <code>diseases.diseases</code>
	 */
	public static final assets.diseases.tables.Diseases DISEASES = new assets.diseases.tables.Diseases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.diseases.tables.records.DiseasesRecord> getRecordType() {
		return assets.diseases.tables.records.DiseasesRecord.class;
	}

	/**
	 * The column <code>diseases.diseases.Disease_ID</code>. 
	 */
	public final org.jooq.TableField<assets.diseases.tables.records.DiseasesRecord, java.lang.Integer> DISEASE_ID = createField("Disease_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>diseases.diseases.Diseases_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.diseases.tables.records.DiseasesRecord, java.lang.String> DISEASES_DESC = createField("Diseases_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>diseases.diseases.Avoid_Food</code>. 
	 */
	public final org.jooq.TableField<assets.diseases.tables.records.DiseasesRecord, java.lang.String> AVOID_FOOD = createField("Avoid_Food", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>diseases.diseases.Avoid_Nutri</code>. 
	 */
	public final org.jooq.TableField<assets.diseases.tables.records.DiseasesRecord, java.lang.String> AVOID_NUTRI = createField("Avoid_Nutri", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>diseases.diseases.Avoid_Exer</code>. 
	 */
	public final org.jooq.TableField<assets.diseases.tables.records.DiseasesRecord, java.lang.String> AVOID_EXER = createField("Avoid_Exer", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>diseases.diseases</code> table reference
	 */
	public Diseases() {
		super("diseases", assets.diseases.Diseases.DISEASES);
	}

	/**
	 * Create an aliased <code>diseases.diseases</code> table reference
	 */
	public Diseases(java.lang.String alias) {
		super(alias, assets.diseases.Diseases.DISEASES, assets.diseases.tables.Diseases.DISEASES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.diseases.tables.records.DiseasesRecord, java.lang.Integer> getIdentity() {
		return assets.diseases.Keys.IDENTITY_DISEASES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.diseases.tables.records.DiseasesRecord> getPrimaryKey() {
		return assets.diseases.Keys.KEY_DISEASES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.diseases.tables.records.DiseasesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.diseases.tables.records.DiseasesRecord>>asList(assets.diseases.Keys.KEY_DISEASES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.diseases.tables.Diseases as(java.lang.String alias) {
		return new assets.diseases.tables.Diseases(alias);
	}
}
