/**
 * This class is generated by jOOQ
 */
package assets.diseases;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diseases extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 903863821;

	/**
	 * The singleton instance of <code>diseases</code>
	 */
	public static final Diseases DISEASES = new Diseases();

	/**
	 * No further instances allowed
	 */
	private Diseases() {
		super("diseases");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			assets.diseases.tables.Diseases.DISEASES);
	}
}
