/**
 * This class is generated by jOOQ
 */
package assets.diseases;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>diseases</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<assets.diseases.tables.records.DiseasesRecord, java.lang.Integer> IDENTITY_DISEASES = Identities0.IDENTITY_DISEASES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<assets.diseases.tables.records.DiseasesRecord> KEY_DISEASES_PRIMARY = UniqueKeys0.KEY_DISEASES_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<assets.diseases.tables.records.DiseasesRecord, java.lang.Integer> IDENTITY_DISEASES = createIdentity(assets.diseases.tables.Diseases.DISEASES, assets.diseases.tables.Diseases.DISEASES.DISEASE_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<assets.diseases.tables.records.DiseasesRecord> KEY_DISEASES_PRIMARY = createUniqueKey(assets.diseases.tables.Diseases.DISEASES, assets.diseases.tables.Diseases.DISEASES.DISEASE_ID);
	}
}
