/**
 * This class is generated by jOOQ
 */
package assets.diseases;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in diseases
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table diseases.diseases
	 */
	public static final assets.diseases.tables.Diseases DISEASES = assets.diseases.tables.Diseases.DISEASES;
}
