/**
 * This class is generated by jOOQ
 */
package assets.fitness;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fitness extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -115151924;

	/**
	 * The singleton instance of <code>fitness</code>
	 */
	public static final Fitness FITNESS = new Fitness();

	/**
	 * No further instances allowed
	 */
	private Fitness() {
		super("fitness");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			assets.fitness.tables.Exercises.EXERCISES);
	}
}
