/**
 * This class is generated by jOOQ
 */
package assets.fitness;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in fitness
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table fitness.exercises
	 */
	public static final assets.fitness.tables.Exercises EXERCISES = assets.fitness.tables.Exercises.EXERCISES;
}
